# Generated by Django 3.2.25 on 2025-04-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engsol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='current_price',
            new_name='cost_estimate',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='initial_date',
            new_name='current_cost',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='initial_price',
            new_name='delivered_date',
        ),
    ]
