# Generated by Django 3.2.25 on 2025-04-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engsol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='cost_estimate',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='information',
            name='current_cost',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
