# Generated by Django 3.2.25 on 2025-04-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engsol', '0002_auto_20250407_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='email',
        ),
    ]
