# Generated by Django 3.2.25 on 2025-04-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engsol', '0002_auto_20250420_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
