# Generated by Django 3.2.25 on 2025-04-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engsol', '0003_auto_20250421_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
