# Generated by Django 3.2.25 on 2025-04-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engsol', '0004_information_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
