# Generated by Django 3.2.25 on 2025-04-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engsol', '0005_alter_ranking_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='cost_estimate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='current_cost',
            field=models.FloatField(),
        ),
    ]
