# Generated by Django 3.2.25 on 2025-04-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='auth_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
